### PR TITLE
Add class for Game state

### PR DESCRIPTION
**Pull request by MarkRobbo**
Adds the representation of the game state at a point in time and a simple program to play the game as a user for test purposes.

### CODE REVIEW

**Comment by MarkRobbo** [comment]
[Class for the Board, with state and methods to return the possible moves](https://trello.com/c/jBEkkY0f/6-class-for-the-board-with-state-and-methods-to-return-the-possible-moves)

**Comment by MarkRobbo** [comment]
[Simple game model and random play](https://trello.com/c/qgh7BBvD/4-simple-game-model-and-random-play)

**Comment by tornjosh** [comment]
Rand() isn't being seeded for makeRandomMove() so the random games are always the same

**Comment by MarkRobbo** [comment]
Fixed by fcfe9b2

**Pull request merged**
